// <auto-generated />
using System;
using Directory.DataAccess.DbConnection;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Directory.DataAccess.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20220527173548_directorymigration")]
    partial class directorymigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityByDefaultColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Directory.Entity.Concrete.ContactInformation", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("Delete")
                        .HasColumnType("boolean");

                    b.Property<string>("InfoContent")
                        .HasColumnType("text");

                    b.Property<string>("InfoType")
                        .HasColumnType("text");

                    b.Property<DateTime>("ModifyDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("personid")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("personid");

                    b.ToTable("ContactInformation");
                });

            modelBuilder.Entity("Directory.Entity.Concrete.Persons", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<string>("Company")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("Delete")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("ModifyDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Surname")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("Persons");
                });

            modelBuilder.Entity("Directory.Entity.Concrete.ContactInformation", b =>
                {
                    b.HasOne("Directory.Entity.Concrete.Persons", "persons")
                        .WithMany("contactInformations")
                        .HasForeignKey("personid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("persons");
                });

            modelBuilder.Entity("Directory.Entity.Concrete.Persons", b =>
                {
                    b.Navigation("contactInformations");
                });
#pragma warning restore 612, 618
        }
    }
}
